# -*- coding: utf-8 -*-
"""Nimbus-Fall2020-CS146-HW1.ipynb
Name: JIAXUAN XUE
Student ID: 705142227
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JPdHKvBwlTgzwlSKv_SYDM37j6t6XrHw
"""

import sys

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/drive')

# Please append your own directory after ‘/content/drive/My Drive/'
# where you have nutil.py and adult_subsample.csv
### ========== TODO : START ========== ###
# for example: sys.path += ['/content/drive/My Drive/Fall2020-CS146-HW1'] 
sys.path += ['/content/drive/My Drive/Fall2020-CS146-HW1'] 
### ========== TODO : END ========== ###

from nutil import *

# Use only the provided packages!
import math
import csv

from collections import Counter

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedShuffleSplit

######################################################################
# Immutatble classes
######################################################################

class Classifier(object) :
    """
    Classifier interface.
    """

    def fit(self, X, y):
        raise NotImplementedError()

    def predict(self, X):
        raise NotImplementedError()


class MajorityVoteClassifier(Classifier) :

    def __init__(self) :
        """
        A classifier that always predicts the majority class.

        Attributes
        --------------------
            prediction_ -- majority class
        """
        self.prediction_ = None

    def fit(self, X, y) :
        """
        Build a majority vote classifier from the training set (X, y).

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples
            y    -- numpy array of shape (n,), target classes

        Returns
        --------------------
            self -- an instance of self
        """
        majority_val = Counter(y).most_common(1)[0][0]
        self.prediction_ = majority_val
        return self

    def predict(self, X) :
        """
        Predict class values.

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples

        Returns
        --------------------
            y    -- numpy array of shape (n,), predicted classes
        """
        if self.prediction_ is None :
            raise Exception("Classifier not initialized. Perform a fit first.")

        n,d = X.shape
        y = [self.prediction_] * n
        return y

######################################################################
# Mutatble classes
######################################################################

class RandomClassifier(Classifier) :

    def __init__(self) :
        """
        A classifier that predicts according to the distribution of the classes.

        Attributes
        --------------------
            probabilities_ -- class distribution dict (key = class, val = probability of class)
        """
        self.probabilities_ = None

    def fit(self, X, y) :
        """
        Build a random classifier from the training set (X, y).

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples
            y    -- numpy array of shape (n,), target classes

        Returns
        --------------------
            self -- an instance of self
        """

        ### ========== TODO : START ========== ###
        # part b: set self.probabilities_ according to the training set
        c = Counter(y)
        self.probabilities_ = {0:c[0]/len(y), 1:c[1]/len(y)}

        ### ========== TODO : END ========== ###

        return self

    def predict(self, X, seed=1234) :
        """
        Predict class values.

        Parameters
        --------------------
            X    -- numpy array of shape (n,d), samples
            seed -- integer, random seed

        Returns
        --------------------
            y    -- numpy array of shape (n,), predicted classes
        """
        if self.probabilities_ is None :
            raise Exception("Classifier not initialized. Perform a fit first.")
        np.random.seed(seed)

        ### ========== TODO : START ========== ###
        # part b: predict the class for each test example
        # hint: use np.random.choice (be careful of the parameters)
        y = np.random.choice([0, 1], X.shape[0], p=[self.probabilities_[0], self.probabilities_[1]])

        
        ### ========== TODO : END ========== ###

        return y

######################################################################
# Immutatble functions
######################################################################

def plot_histograms(X, y, Xnames, yname) :
    n,d = X.shape  # n = number of examples, d =  number of features
    fig = plt.figure(figsize=(20,15))
    ncol = 3
    nrow = d // ncol + 1
    for i in range(d) :
        fig.add_subplot (nrow,ncol,i+1)
        data, bins, align, labels = plot_histogram(X[:,i], y, Xname=Xnames[i], yname=yname, show = False)
        n, bins, patches = plt.hist(data, bins=bins, align=align, alpha=0.5, label=labels)
        plt.xlabel(Xnames[i])
        plt.ylabel('Frequency')
        plt.legend() #plt.legend(loc='upper left')

    plt.savefig ('histograms.pdf')


def plot_histogram(X, y, Xname, yname, show = True) :
    """
    Plots histogram of values in X grouped by y.

    Parameters
    --------------------
        X     -- numpy array of shape (n,d), feature values
        y     -- numpy array of shape (n,), target classes
        Xname -- string, name of feature
        yname -- string, name of target
    """

    # set up data for plotting
    targets = sorted(set(y))
    data = []; labels = []
    for target in targets :
        features = [X[i] for i in range(len(y)) if y[i] == target]
        data.append(features)
        labels.append('%s = %s' % (yname, target))

    # set up histogram bins
    features = set(X)
    nfeatures = len(features)
    test_range = list(range(int(math.floor(min(features))), int(math.ceil(max(features)))+1))
    if nfeatures < 10 and sorted(features) == test_range:
        bins = test_range + [test_range[-1] + 1] # add last bin
        align = 'left'
    else :
        bins = 10
        align = 'mid'

    # plot
    if show == True:
        plt.figure()
        n, bins, patches = plt.hist(data, bins=bins, align=align, alpha=0.5, label=labels)
        plt.xlabel(Xname)
        plt.ylabel('Frequency')
        plt.legend() #plt.legend(loc='upper left')
        plt.show()

    return data, bins, align, labels

######################################################################
# Mutatble functions
######################################################################

def error(clf, X, y, ntrials=100, test_size=0.2) :
    """
    Computes the classifier error over a random split of the data,
    averaged over ntrials runs.

    Parameters
    --------------------
        clf         -- classifier
        X           -- numpy array of shape (n,d), features values
        y           -- numpy array of shape (n,), target classes
        ntrials     -- integer, number of trials

    Returns
    --------------------
        train_error -- float, training error
        test_error  -- float, test error
        f1_score    -- float, test "micro" averaged f1 score
    """

    ### ========== TODO : START ========== ###
    # compute cross-validation error using StratifiedShuffleSplit over ntrials
    # hint: use train_test_split (be careful of the parameters)
    train_error = 0
    test_error = 0
    f1 = 0
    sss = StratifiedShuffleSplit(n_splits=ntrials, test_size=test_size, random_state=0)
    for train_index, test_index in sss.split(X, y):
      X_train, X_test = X[train_index], X[test_index]
      y_train, y_test = y[train_index], y[test_index]
      clf.fit(X_train, y_train)
      y_pred_train = clf.predict(X_train)
      train_error += 1 - metrics.accuracy_score(y_train, y_pred_train, normalize=True)
      y_pred_test = clf.predict(X_test)
      test_error += 1 - metrics.accuracy_score(y_test, y_pred_test, normalize=True)
      f1 += metrics.f1_score(y_test, y_pred_test, average='micro')
    
    train_error /= ntrials
    test_error /= ntrials
    f1 /= ntrials
    f1_score = f1
   
    ### ========== TODO : END ========== ###

    return train_error, test_error, f1_score

######################################################################
# Immutatble functions
######################################################################


def write_predictions(y_pred, filename, yname=None) :
    """Write out predictions to csv file."""
    out = open(filename, 'wb')
    f = csv.writer(out)
    if yname :
        f.writerow([yname])
    f.writerows(list(zip(y_pred)))
    out.close()

######################################################################
# main
######################################################################

def main():
    
    
    
    # load adult_subsample dataset with correct file path
    ### ========== TODO : START ========== ###
    data_file =  "/content/drive/My Drive/Fall2020-CS146-HW1/adult_subsample.csv"
    ### ========== TODO : END ========== ###
    



    data = load_data(data_file, header=1, predict_col=-1)

    X = data.X; Xnames = data.Xnames
    y = data.y; yname = data.yname
    n,d = X.shape  # n = number of examples, d =  number of features

    

    plt.figure()
    #========================================
    # part a: plot histograms of each feature
    print('Plotting...')
    plot_histograms (X, y, Xnames=Xnames, yname=yname)
    




    ### ========== TODO : START ========== ###
    # part i: Preprocess X (e.g., normalize)
    scaler = StandardScaler()
    X = scaler.fit_transform(X)
    # print('preprocesed mean')
    # print(np.mean(X, axis = 0))
    # print('proprecesed sd')
    # print(np.std(X, axis = 0))
    ### ========== TODO : END ========== ###




    #========================================
    # train Majority Vote classifier on data
    print('Classifying using Majority Vote...')
    clf = MajorityVoteClassifier() # create MajorityVote classifier, which includes all model parameters
    clf.fit(X, y)                  # fit training data using the classifier
    y_pred = clf.predict(X)        # take the classifier and run it on the training data
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('\t-- training error: %.3f' % train_error)





    ### ========== TODO : START ========== ###
    # part b: evaluate training error of Random classifier
    print('Classifying using Random...')
    r_clf = RandomClassifier()
    r_clf.fit(X,y)
    yr_pred = r_clf.predict(X)
    train_error = 1 - metrics.accuracy_score(y, yr_pred, normalize=True)
    print('\t-- training error: %.3f' % train_error)
    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part c: evaluate training error of Decision Tree classifier
    print('Classifying using Decision Tree...')
    dt_clf = DecisionTreeClassifier(criterion="entropy")
    dt_clf.fit(X, y)
    y_pred = dt_clf.predict(X)
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('\t-- training error: %.3f' % train_error)
    ### ========== TODO : END ========== ###






    ### ========== TODO : START ========== ###
    # part d: evaluate training error of k-Nearest Neighbors classifier
    # use k = 3, 5, 7 for n_neighbors
    print('Classifying using k-Nearest Neighbors...')
    knn3 = KNeighborsClassifier(n_neighbors=3)
    knn3.fit(X,y)
    y_pred = knn3.predict(X)
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('k=3')
    print('\t-- training error: %.3f' % train_error)
    knn5 = KNeighborsClassifier(n_neighbors=5)
    knn5.fit(X,y)
    y_pred = knn5.predict(X)
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('k=5')
    print('\t-- training error: %.3f' % train_error)
    knn7 = KNeighborsClassifier(n_neighbors=7)
    knn7.fit(X,y)
    y_pred = knn7.predict(X)
    train_error = 1 - metrics.accuracy_score(y, y_pred, normalize=True)
    print('k=7')
    print('\t-- training error: %.3f' % train_error)
    
    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part e: use cross-validation to compute average training and test error of classifiers
    print('Investigating various classifiers...')
    
    print('Investigating RandomClassifier')
    train_error, test_error, F1_score = error(r_clf, X, y)
    print('\t-- training error: %.3f' % train_error)
    print('\t-- test error: %.3f' % test_error)
    print('\t-- f1 score: %.3f' % F1_score)
    
    print('Investigating MajorityVoteClassifier')
    train_error, test_error, F1_score = error(clf, X, y)
    print('\t-- training error: %.3f' % train_error)
    print('\t-- test error: %.3f' % test_error)
    print('\t-- f1 score: %.3f' % F1_score)
    
    print('Investigating DecisionTreeClassifier')
    train_error, test_error, F1_score = error(dt_clf, X, y)
    print('\t-- training error: %.3f' % train_error)
    print('\t-- test error: %.3f' % test_error)
    print('\t-- f1 score: %.3f' % F1_score)

    print('Investigating KNeighborsClassifier( k = 5 )')
    train_error, test_error, F1_score = error(knn5, X, y)
    print('\t-- training error: %.3f' % train_error)
    print('\t-- test error: %.3f' % test_error)
    print('\t-- f1 score: %.3f' % F1_score)

    
    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part f: use 10-fold cross-validation to find the best value of k for k-Nearest Neighbors classifier
    print('Finding the best k...')
    k = list(range(1,50,2))
    validation_error = []
    k_best = 0
    score_max = 0
    for i in k:
      knn = KNeighborsClassifier(n_neighbors=i)
      scores = cross_val_score(knn,X,y,cv=10)
      validation_error.append(1-sum(scores)/len(scores))
      if sum(scores)/len(scores)>score_max:
        score_max = sum(scores)/len(scores)
        k_best = i
    plt.figure()
    plt.plot(k, validation_error,label='validation_error')
    plt.xlabel('Number of Neighbors')
    plt.ylabel('Validation Error')
    plt.legend()
    plt.show()
    print('The best value of k is %d' % k_best)

    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part g: investigate decision tree classifier with various depths
    print('Investigating depths...')
    depth = list(range(1,21))
    train_errors = []
    test_errors = []
    smallest = 1
    d_best = 1
    for d in depth:
        dt_clf = DecisionTreeClassifier(criterion='entropy', max_depth=d)
        train_error, test_error,f1_score = error(dt_clf,X,y)
        train_errors.append(train_error)
        test_errors.append(test_error)
        if test_error < smallest:
          smallest = test_error
          d_best = d
    plt.figure()
    plt.plot(depth, train_errors, label='train_error')
    plt.plot(depth, test_errors, label='test_error')
    plt.xlabel('Depth')
    plt.ylabel('Validation Error')
    plt.legend()
    plt.show()
    print('The best depth limit to use for this data is %d' % d_best)


    ### ========== TODO : END ========== ###





    ### ========== TODO : START ========== ###
    # part h: investigate decision tree and k-Nearest Neighbors classifier with various training set sizes
    from sklearn.model_selection import train_test_split

    #helper function that returns the training error and testing error caused 
    #by a certain training size(train_prop) on the same test data with a certain classifier
    def experience_error(clf, X_train, y_train, X_test, y_test, train_prop, n_trials = 10):
      train_error = 0
      test_error = 0
      for i in range(n_trials):
          if train_prop == 1:
              clf.fit(X_train, y_train)
              y_pred_train = clf.predict(X_train)
              train_error += 1 - metrics.accuracy_score(y_train, y_pred_train, normalize=True)
              y_pred_test = clf.predict(X_test)
              test_error += 1 - metrics.accuracy_score(y_test, y_pred_test, normalize=True)
          else:
              X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(X_train, y_train, test_size=1-train_prop, random_state=42)
              clf.fit(X_train_s, y_train_s)
              y_pred_train = clf.predict(X_train_s)
              train_error += 1 - metrics.accuracy_score(y_train_s, y_pred_train, normalize=True)
              y_pred_test = clf.predict(X_test)
              test_error += 1 - metrics.accuracy_score(y_test, y_pred_test, normalize=True)
      
      train_error /= n_trials
      test_error /= n_trials

      return train_error, test_error

    # first generate a random 90/10 split of the training data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
    testing_proprotion=list(range(1,11))
    dt_train_errors = []
    dt_test_errors = []
    knn_train_errors = []
    knn_test_errors = []
    # collect training errors and test errors for dc and knn
    for t in testing_proprotion:
        dt_clf = DecisionTreeClassifier(criterion='entropy', max_depth=5)
        dt_train_error, dt_test_error = experience_error(dt_clf,X_train, y_train, X_test, y_test, train_prop = t*0.1)
        dt_train_errors.append(dt_train_error)
        dt_test_errors.append(dt_test_error)
        knn_clf = KNeighborsClassifier(n_neighbors=27)
        knn_train_error, knn_test_error = experience_error(knn_clf,X_train, y_train, X_test, y_test, train_prop = t*0.1)
        knn_train_errors.append(knn_train_error)
        knn_test_errors.append(knn_test_error)
   
    amount_of_training = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
    # plot the graph
    plt.figure()
    plt.plot(amount_of_training, dt_train_errors, label='dt_train_error')
    plt.plot(amount_of_training, dt_test_errors, label='dt_test_error')
    plt.plot(amount_of_training, knn_train_errors, label='knn_train_error')
    plt.plot(amount_of_training, knn_test_errors, label='knn_test_error')
    plt.xlabel('Training Amount')
    plt.ylabel('Validation Error')
    plt.legend()
    plt.show()
    
    ### ========== TODO : END ========== ###



    print('Done')


if __name__ == "__main__":
    main()
