# -*- coding: utf-8 -*-
"""Nimbus-Fall2020-CS146-HW4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bulQVpnCEUITs9_-lvMhyV8vpZv2rTR4
"""

# To add your own Drive Run this cell.
from google.colab import drive
drive.mount('/content/drive')

"""
Author      : Zeyuan Chen, adapted from Yi-Chieh Wu, Sriram Sankararman
Description : Twitter
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn import metrics 
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.mixture import GaussianMixture
from sklearn.metrics.cluster import adjusted_rand_score

import pandas as pd
### ========== TODO : START ========== ###
# append you own path to the tweeter_df.txt file after "/content/drive/My Drive/"
# i.e. "/content/drive/My Drive/CM146HW4/tweets_df.txt"
tweets_df = pd.read_csv("/content/drive/My Drive/Fall2020-CS146-HW4/tweets_df.txt", index_col = 0)
### ========== TODO : END ========== ###

X = tweets_df.values[:,:-2]
y = tweets_df.values[:, -2]
movies = tweets_df.values[:, -1]

train_idx = np.where((movies == 1) | (movies == 3))[0]
dev_idx   = np.where(movies == 2)[0]
test_idx  = np.where(movies == 0)[0]

X_train, X_dev, X_test = X[train_idx,], X[dev_idx,], X[test_idx,]
y_train, y_dev, y_test = y[train_idx,], y[dev_idx,], y[test_idx,]

### ========== TODO : START ========== ###
# part 4.1a: show the train and development set f1-score when C is set to 10^-3 10^-2 10^-1 1, 10, 100, 1000
#            This can typically be done in 20 lines or so
C_value=[0.001,0.01,0.1,1,10,100,1000]
f1_train=[]
f1_dev=[]
for i in C_value:
  clf = SVC(C=i, kernel='linear')
  clf.fit(X_train, y_train)                  
  y_pred_train = clf.predict(X_train)
  y_pred_dev = clf.predict(X_dev)
  f1_train.append(metrics.f1_score(y_train,y_pred_train))
  f1_dev.append(metrics.f1_score(y_dev,y_pred_dev))

plt.figure()
plt.semilogx(C_value, f1_train, label='train_score')
plt.semilogx(C_value, f1_dev, label='dev_score')
plt.xlabel('C values')
plt.ylabel('F1 score')
plt.legend()
plt.show()

print(f1_train)
print(f1_dev)




### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.1b: select the best model based on development set f1-score 
#            retrain the model on train and dev set
#            test the final model on the test set
#            This can typically be done in 5 lines or so
# print(X_train.shape)
# print(X_dev.shape)
new_train_index= np.where((movies == 1) | (movies == 3)|(movies == 2))[0]
X_newtrain=X[new_train_index,]
y_newtrain=y[new_train_index,]
# print(X_newtrain.shape)
clf = SVC(C=1, kernel='linear') 
clf.fit(X_newtrain,y_newtrain)  
y_pred_test = clf.predict(X_test)
print(metrics.f1_score(y_test,y_pred_test))


### ========== TODO : END ========== ###

def plot_scatter(embedding_2d, labels, show = True, save_as = None, title = None):
    """
    Visualize 2D data

    Parameters
    --------------------
        embedding_2d   -- numpy array of shape (n,2) samples
        labels         -- numpy array of shape (n,) labels
        show           -- optional boolean indicator on if display the visualziation, default set to True 
        save_as        -- optional string indicating where we should save the figure, default set to None
        title          -- optional string indicating what should be the title, default set to None
    --------------------
        None    
    """
    
    plt.scatter(embedding_2d[:,0], embedding_2d[:,1], c = labels) 
    if title is not None:
        plt.title(title)
    if save_as is not None:
        plt.savefig(save_as)
    if show:
        plt.show()

pca = PCA(n_components=2)
pca.fit(X)
X_embedding = pca.transform(X)

### ========== TODO : START ========== ###
# part 4.2a: visualize the embedding. First color the dots by positive or negative review, then by movies 
#            This can typically be done in 2 lines or so
plt.figure()
plot_scatter(X_embedding, y, show = True, save_as = "PN.png", title = "positive or negative review")
plot_scatter(X_embedding, movies, show = True, save_as = "movie.png", title = "movie review")

### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.2b: First color the dots by Kmeans with 4 components, random initialization, 1 iteration, random_state = 2
#            then by GMM with 4 components, random starting point, 1 iteration and random_state = 0
#            report the adjusted rand score for both
#            This can typically be done in 10 lines or so
clt_KM = KMeans(n_clusters=4, init='random', n_init=1, random_state=2)
clt_KM.fit(X_embedding)
y_KM_pred = clt_KM.predict(X_embedding)
plot_scatter(X_embedding, y_KM_pred, save_as='KMeans.png', title='KMeans clustering')
print('KMean adjusted random score:', adjusted_rand_score(movies,y_KM_pred ))
clt_GMM = GaussianMixture(n_components=4, random_state=0, init_params='random')
clt_GMM.fit(X_embedding)
y_GMM_pred = clt_GMM.predict(X_embedding)
plot_scatter(X_embedding, y_GMM_pred, save_as='GMM.png', title='GMM clustering')
print('GMM adjusted random score:', adjusted_rand_score(movies, y_GMM_pred))
### ========== TODO : END ========== ###

### ========== TODO : START ========== ###
# part 4.2c: First color the dots by Kmeans with 4 components, random initialization, 100 iterations, random_state = 2
#            then by GMM with 4 components, random starting point, 100 iterations and random_state = 0
#            report then adjusted rand score for both
#            This can typically be done in 10 lines or so
clt_KM = KMeans(n_clusters=4, init='random', n_init=100, random_state=2)
clt_KM.fit(X_embedding)
y_KM_pred = clt_KM.predict(X_embedding)
plot_scatter(X_embedding, y_KM_pred, save_as='KMeans.png', title='KMeans clustering')
print('KMean adjusted random score:', adjusted_rand_score(movies,y_KM_pred ))
clt_GMM = GaussianMixture(n_components=4, random_state=0, init_params='random', n_init=100)
clt_GMM.fit(X_embedding)
y_GMM_pred = clt_GMM.predict(X_embedding)
plot_scatter(X_embedding, y_GMM_pred, save_as='GMM.png', title='GMM clustering')
print('GMM adjusted random score:', adjusted_rand_score(movies, y_GMM_pred))
### ========== TODO : END ========== ###